# Generated by Django 3.2.6 on 2021-09-12 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submit_day',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=400),
        ),
    ]
