# Generated by Django 3.2.6 on 2021-09-12 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210912_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submit_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
