# Generated by Django 3.2.6 on 2021-09-12 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_contact_submit_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submit_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
